### ISSUE TITLE
UI/UXデザインの改善

### ISSUE THREAD

**Issue by nisshi-dev** [Code-for-Yamaguchi/codeforyamaguchi.org#1]
より多くのサイト閲覧者がコミュニティに興味を持ってくれるように、UI/UXデザインを改善する

**Comment by nishidayoshikatsu** [comment]
まずは、TOPのテキストをいいかんじにする
![image](https://user-images.githubusercontent.com/42875682/116528559-f03f7f80-a916-11eb-8700-a4e0115b863e.png)

**Comment by nishidayoshikatsu** [comment]
スマホ版ページのヘッダーの高さが少し大きい気がするので、少し調整
![image](https://user-images.githubusercontent.com/42875682/116577390-6362e900-a94b-11eb-8a5f-87657dca21b6.png)

**Comment by nishidayoshikatsu** [comment]
参加方法のコンテンツを追加する

**Comment by nishidayoshikatsu** [comment]
開催予定のイベントのリストをcarouselで表示する

**Comment by nishidayoshikatsu** [comment]
各詳細ページを作成
