### ISSUE TITLE
イベント画像未反映部分反映

### ISSUE THREAD

**Issue by Myaon** [Code-for-Yamaguchi/codeforyamaguchi.org#34]
https://codeforyamaguchi.org/events

**Comment by nisshi-dev** [comment]
#29

**Comment by Myaon** [comment]
再デプロイにつき、更新Done
https://dash.cloudflare.com/6df6cf67854b9687274be0eda1099353/pages/view/codeforyamaguchi-org/7ee5ee27-3288-4830-94ca-6021f1479788
https://codeforyamaguchi.org/members
