### ISSUE TITLE
ESLint の設定の見直し

### ISSUE THREAD

**Issue by watagit** [Code-for-Yamaguchi/codeforyamaguchi.org#4]
ESLint からの警告が競合しているので、設定を見直して変更したい。

**Comment by nishidayoshikatsu** [comment]
エラーその１
'React' must be in scope when using JSX

以下を.eslint.jsonに追加で解決
> "react/react-in-jsx-scope": "off",

**Comment by nishidayoshikatsu** [comment]
エラーその２
Component definition is missing display name react/display-name

以下を.eslint.jsonに追加で解決
displayname付けることを推奨されているので後々修正
> "react/display-name": "off"
参考: https://stackoverflow.com/questions/62011669/eslint-component-definition-is-missing-displayname

参考:

**Comment by nishidayoshikatsu** [comment]
エラーその３

`"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`  react/no-unescaped-entities

その通りに変更
